# width_heuristics = "Scaled"
max_width = 100
# array_width = 60
binop_separator = "Back"
brace_style = "SameLineWhere"
# chain_width = 60
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 30
fn_args_layout = "Tall"
# fn_call_width = 30
fn_single_line = false
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
struct_field_align_threshold = 0
wrap_comments = true